trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)

- script: dotnet restore ThreadPilot.sln
  displayName: 'Restore dependencies'

- script: dotnet build ThreadPilot.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

- script: dotnet test ThreadPilot.sln --configuration $(buildConfiguration) --no-build --logger trx
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'